In [1]:
import numpy as np
import pandas as pd

In [3]:
# 1. CARGA DE DATOS
data = pd.read_csv('../data/sales_data.csv')

x = data['advertising'].to_numpy()
y = data['sales'].to_numpy()

print(data)
print(x)
print(y)

   advertising  sales
0            1    3.2
1            2    4.8
2            3    7.3
3            4    8.7
4            5   11.1
5            6   12.8
6            7   15.2
7            8   16.7
[1 2 3 4 5 6 7 8]
[ 3.2  4.8  7.3  8.7 11.1 12.8 15.2 16.7]


In [4]:
# 2. MATRIZ DE DISEÑO
X = np.column_stack((np.ones(len(x)), x))

print('X:')
print(X)
print('Shape X:', X.shape)
print('Shape y:', y.shape)

X:
[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [1. 8.]]
Shape X: (8, 2)
Shape y: (8,)


In [12]:
# 3. OPERACIONES MATRICIALES
XtX = X.T @ X
Xty = X.T @ y

print('X.T @ X:')
print(XtX)
print('X.T @ y:')
print(Xty)
print('Shape XtX:', XtX.shape)
print('Shape X.T:', X.T.shape)

X.T @ X:
[[  8.  36.]
 [ 36. 204.]]
X.T @ y:
[ 79.8 441.8]
Shape XtX: (2, 2)
Shape X.T: (2, 8)


In [7]:
# 4. ESTIMACION DE PARAMETROS
B, residuals, rank, s = np.linalg.lstsq(X, y, rcond=None)
beta = B

beta_0 = beta[0]
beta_1 = beta[1]

print('Beta 0:', beta_0)
print('Beta 1:', beta_1)

Beta 0: 1.1142857142857154
Beta 1: 1.969047619047618


In [8]:
# 5. PREDICCION
x_new = np.array([1, 9])
prediction = x_new @ beta

print('Prediction:', prediction)

Prediction: 18.835714285714275


In [9]:
# 6. PREDICCIONES DEL DATASET
y_pred = X @ beta

print(y_pred)

[ 3.08333333  5.05238095  7.02142857  8.99047619 10.95952381 12.92857143
 14.89761905 16.86666667]


In [10]:
# 7. ERROR
errors = y - y_pred
error_norm = np.linalg.norm(errors)

print('Error vector:')
print(errors)
print('Error norm:')
print(error_norm)

Error vector:
[ 0.11666667 -0.25238095  0.27857143 -0.29047619  0.14047619 -0.12857143
  0.30238095 -0.16666667]
Error norm:
0.6283008075451634


In [ ]:
# 8. PREGUNTAS
# 1. Que representa cada fila de X?
# Respuesta:
# 1. Que representa cada fila de X?
# Respuesta: Cada fila representa una observacion del dataset. Contiene el termino independiente 1 y el valor de advertising.
#
# 2. Por que X contiene una primera columna de unos?
# Respuesta:
# 2. Por que X contiene una primera columna de unos?
# Respuesta: La columna de unos permite incluir el intercepto beta_0 en el modelo lineal.
#
# 3. Cual es la dimension de X.T @ X y por que?
# Respuesta:
# 3. Cual es la dimension de X.T @ X y por que?
# Respuesta: Su dimension es 2 x 2 porque X tiene 2 columnas y X.T tiene dimension 2 x 8.
#
# 4. Que representa beta_0 dentro de este problema?
# Respuesta:
# 4. Que representa beta_0 dentro de este problema?
# Respuesta: beta_0 es el intercepto: las ventas estimadas cuando advertising vale 0.
#
# 5. Que representa beta_1 dentro de este problema?
# Respuesta:
# 5. Que representa beta_1 dentro de este problema?
# Respuesta: beta_1 es la pendiente: el cambio estimado en sales por cada unidad adicional de advertising.
#
# 6. Que significa que la norma del error sea pequena?
# Respuesta:
# 6. Que significa que la norma del error sea pequena?
# Respuesta: Significa que las predicciones estan cerca de los valores reales y el ajuste del modelo es bueno.
#
# 7. Por que X @ beta permite obtener todas las predicciones simultaneamente?
# Respuesta:
# 7. Por que X @ beta permite obtener todas las predicciones simultaneamente?
# Respuesta: Cada fila de X representa una observacion y el producto con beta calcula su prediccion; por eso devuelve todas en un solo vector.